"""
Django settings for form_builder_project project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'

# file manager app — only sees this folder
FILE_MANAGER_ROOT = BASE_DIR / 'media' / 'file_manager'


# forms app — only sees this folder
FORMS_MEDIA_ROOT  = BASE_DIR / 'media' / 'forms'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-r^o&04zndy#_yr#zlfnn-v^)(ea9kd$rr=mq4^+6&@mzz4v(jg'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Custom users pointing
AUTH_USER_MODEL = 'accounts.CustomUser'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'forms',
    'storage',
    'submissions',
    'drf_spectacular',
    'accounts',
    'rest_framework_simplejwt.token_blacklist',
    'djoser',
]
DJOSER = {
    'USER_ID_FIELD': 'username',
    'LOGIN_ID_FIELD': 'email',
}

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        # default rates — apply to all views unless overridden
        'anon':               '30/minute',    # unauthenticated requests
        'user':               '200/minute',   # authenticated requests

        # auth specific — strictest limits
        'auth_login':         '5/minute',     # login attempts per IP
        'auth_register':      '3/minute',     # registration attempts per IP

        # upload specific
        'file_upload':        '20/minute',    # single file uploads
        'folder_upload':      '5/minute',     # folder structure uploads

        # download specific
        'file_download':      '30/minute',    # single file downloads
        'bulk_download':      '5/minute',     # zip archive generation

        # expensive operations
        'storage_stats':      '10/minute',    # walks entire disk
        'file_search':        '30/minute',    # directory listing and search

        # destructive operations
        'bulk_delete':        '10/minute',    # bulk deletions

        # share operations
        'share_create':       '20/minute',    # generating share links
    }

}

# JWT configuration
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME':  timedelta(minutes=60),  # access token expires in 60 min
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),       # refresh token expires in 7 days
    'ROTATE_REFRESH_TOKENS':  True,                    # issue new refresh token on every refresh
    'BLACKLIST_AFTER_ROTATION': True,                  # blacklist old refresh tokens
    'AUTH_HEADER_TYPES': ('Bearer',),                  # Authorization: Bearer <token>
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'File Manager API',
    'DESCRIPTION': 'API for managing files and folders',
    'VERSION': '1.0.0',
}

# CORS settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

CORS_ALLOW_CREDENTIALS = True

# For development, allow all origins
CORS_ALLOW_ALL_ORIGINS = True

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'form_builder_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'form_builder_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'delete-expired-share-links': {
        'task': 'yourapp.tasks.delete_expired_share_links',
        'schedule': crontab(hour=0, minute=0),  # runs every day at midnight
    }
}