# Generated by Django 6.0.3 on 2026-03-26 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemWideStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_users', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('new_users', models.IntegerField(default=0)),
                ('total_forms', models.IntegerField(default=0)),
                ('total_submissions', models.IntegerField(default=0)),
                ('total_files', models.IntegerField(default=0)),
                ('total_storage', models.BigIntegerField(default=0)),
                ('total_logins', models.IntegerField(default=0)),
                ('total_api_calls', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'System Statistics',
                'verbose_name_plural': 'System Statistics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DashboardStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_folders', models.IntegerField(default=0)),
                ('total_files', models.IntegerField(default=0)),
                ('total_storage_used', models.BigIntegerField(default=0)),
                ('total_storage_limit', models.BigIntegerField(default=5368709120)),
                ('total_forms_created', models.IntegerField(default=0)),
                ('total_submissions_received', models.IntegerField(default=0)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('total_logins', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dashboard Statistics',
                'verbose_name_plural': 'Dashboard Statistics',
            },
        ),
        migrations.CreateModel(
            name='UserActivitySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('files_uploaded', models.IntegerField(default=0)),
                ('files_downloaded', models.IntegerField(default=0)),
                ('folders_created', models.IntegerField(default=0)),
                ('forms_created', models.IntegerField(default=0)),
                ('submissions_made', models.IntegerField(default=0)),
                ('storage_added', models.BigIntegerField(default=0)),
                ('storage_removed', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Summary',
                'verbose_name_plural': 'Activity Summaries',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
