# Generated by Django 6.0.4 on 2026-05-08 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharedfile',
            name='created_at',
        ),
        migrations.AddField(
            model_name='sharedfile',
            name='item_type',
            field=models.CharField(choices=[('file', 'File'), ('folder', 'Folder')], default='file', max_length=10),
        ),
    ]
