# Generated by Django 6.0.4 on 2026-05-08 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_remove_sharedfile_created_at_sharedfile_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedfile',
            name='is_viewable',
            field=models.BooleanField(default=False),
        ),
    ]
