# Generated by Django 6.0.4 on 2026-05-09 10:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_sharedfile_is_viewable'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedfile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
