# Generated by Django 6.0.4 on 2026-05-09 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_sharedfile_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrashedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_path', models.CharField(max_length=500)),
                ('trash_path', models.CharField(max_length=500)),
                ('item_type', models.CharField(choices=[('file', 'File'), ('folder', 'Folder')], default='file', max_length=10)),
                ('item_name', models.CharField(max_length=255)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('trashed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trashed_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-trashed_at'],
            },
        ),
    ]
